### PR TITLE
Fixes: #1035

### PR DESCRIPTION
**Pull request by jvmanji**
See discussion in: https://github.com/nelmio/alice/issues/1035

### CODE REVIEW

**Comment by theofidry** [comment]
👍 would it be possible to have a test case as well to avoid regressions in the future?

**Comment by jvmanji** [comment]
I've added test case in `tests/Generator/NamedArgumentsResolverTest.php`, because I think it belongs there. Can you check whether naming of things suits you? Feel free to send any remarks.

**Comment by kotbehemot53** [comment]
Can anyone merge it? It would be really nice to have the fix in the base branch.

**Comment by theofidry** [comment]
Thank you @jvmanji

**Pull request merged**
