### PR TITLE
Add current() in identity() support

### PR DESCRIPTION
**Pull request by c1tru55**

### CODE REVIEW

**Comment by Seldaek** [comment]
Could you add tests for this?

**Comment by c1tru55** [comment]
@Seldaek done

**Comment by Seldaek** [comment]
Ok thanks, I'll merge but it'd be great to do backport that new feature also on the master branch though otherwise we have a feature missing in 2.0.

**Comment by c1tru55** [comment]
Ideally we need not only support of `current()` inside provider, but support of calling provider function inside another provider. I mean some kind of recursive processing arguments. But unfortunately I have no time for that now, so I add only `current()` support on top level. I think you or maintainer can implement it much faster.

**Comment by egoista** [comment]
sorry for the dumb question,

I'm using hautelook/alice-bundle, have someway to use this PR with hautelook/alice-bundle?

**Comment by c1tru55** [comment]
@Seldaek can you please add new tag for this feature?

**Comment by FoxxMD** [comment]
+1 for having this in the master branch

**Comment by fschaeffer** [comment]
+1 for master branch, just discovered this very useful method and use it in 1.x branch but will update soon to 2.x ...

**Comment by fschaeffer** [comment]
@egoista as hautelook/alice-bundle is just a wrapper you can use it as every other function
```
mediaThumb{1..100}:
        mediaType: @mediaTypethumb
        name: <identity(current() + 100)>.jpg
        asset: @assetInstanceIn<current()>
```

**Comment by pwm** [comment]
+1, I just ran into this as well. It would be greatly useful.

**Comment by ktounet** [comment]
very useful feature! master branch ?

**Comment by fschaeffer** [comment]
Any news on this feature for 2.x/master? This issue prevents updating to 2.x as the <current()>-usage in identity is really usefull...

**Comment by theofidry** [comment]
@fschaeffer :+1:

**Pull request merged**
