### PR TITLE
Fix faker regexp when we want to generate SR_LATN names

### PR DESCRIPTION
**Pull request by tifabien**
Fix the regex when we want to generate SR_LATN names.

### CODE REVIEW

**Comment by theofidry** [comment]
Hi! Thanks for you contribution. I'm perfectly fine with the change but it would be neat if you could add a test for it as well. I think a simple case in `LoaderIntegrationTest` in `provideFixturesToGenerate` or something like that would do :)

**Comment by tifabien** [comment]
The LoaderIntegrationTest class seems to be only on the master branch. Is there any equivalent for the 2.x branch?

**Comment by theofidry** [comment]
Sorry I didn't notice this was for 2.x. You have [LoaderTest.php](https://github.com/nelmio/alice/blob/2.x/tests/Nelmio/Alice/Fixtures/LoaderTest.php)

**Comment by tifabien** [comment]
I just added the unit test. I'll have a look at the 3.x branch and let you know if it's OK!

**Comment by tifabien** [comment]
Just checked and all seems OK on the master branch :)

**Comment by theofidry** [comment]
Alright, I'll try to have a look this week. I'm ok with the feature but I would like the build to be green first :)

**Comment by tifabien** [comment]
it seems related to the deprecation notice introduced in SF 3.4 regarding the tests/Nelmio/Alice/Fixtures/Parser/Files/Yaml/file_with_constants.yml:10 file

**Comment by theofidry** [comment]
Yep, it's probably easy to fix, but it needs to be fixed first nonetheless

**Comment by theofidry** [comment]
Thank you @tifabien!

**Pull request merged**
