### PR TITLE
Add support for named parameters in constructor and functions

### LINKED ISSUE #594: Support constructor named properties
For:

``` yaml
User:
    user0:
        __construct:
            - bob
            - Bob
            - '1980-10-10'
            - bob@example.org
            - 42
```

It would be better if we could do:

``` yaml
User:
    user0:
        __construct:
            username: bob
            fullname: Bob
            dateOfBirth:  '1980-10-10'
            email: bob@example.org
            favoriteNumber: 42
```

Besides being easier to understand (IMO), it also gives the possibility to re-order the properties. That said this does rely on the name of PHP variable, i.e. the constructor must look like this:

``` php
class User
{
  public function __construct($username, $fullname, $dateOfBirth, $email, $favoriteNumber)
  {
    //...
  }
}
```

And changing a variable name _can_ break the fixture code.

@tshelburne WDYT?

### PR DESCRIPTION
**Pull request by theofidry**
Closes #594.

- [ ] Add tests for the support in functions
- [ ] Add tests for support with the usage of flags
- [ ] Finish the PR (add missing tests + cleanup)

@tshelburne could you please double check the integration tests (in `LoaderIntegrationTest` to see if that makes sense to your or if I'm missing something? Cheers

### CODE REVIEW

**Comment by tshelburne** [comment]
@theofidry The test itself looks good to me after a quick review. Thorough job.

**Comment by theofidry** [comment]
Ok major disappointment, this cannot be done unless in a very limited context:

- In the case where the factory is a service, the service is resolved at generation time while we need info (reflection) on the factory method during the denormalization
- In the case of a function, the point above is even more true
- The two points above are still true (although becomes doable) if the factory/method is a static call on another function

I'm also not found of the idea of having it working in 1 case and not elsewhere, that would only be confusing IMO.

**Comment by julienfalque** [comment]
I was about to open a feature request for this but Github helped me find #594 :)

Is [the reason this was aborted](https://github.com/nelmio/alice/pull/599#issuecomment-258318056) still true? I don't know the internals of the library, how important is it for named arguments to be resolved at denormalization time? Can't this be done at instanciation time (when the factory is supposed to be resolved)?

**Comment by theofidry** [comment]
I think that maybe could be done by passing the names to the denormalized object and at instantiation doing extra work to handle those names instead of a simple array of arguments

**Comment by julienfalque** [comment]
Do you mind reopening #594? I might give it a try if I find time.

**Pull request closed without merging**
