### PR TITLE
Fixed error with empty input

### PR DESCRIPTION
**Pull request by enumag**
With empty input I got this error:

```
Warning: array_merge() expects at least 1 parameter, 0 given
```

### CODE REVIEW

**Comment by tshelburne** [comment]
Fair - out of curiosity, why are you passing empty input to this?

Please add a regression test, happy to merge afterwards.

**Comment by enumag** [comment]
I'm new to Alice so I just ran into this randomly when my fixtures.yml file was empty.

I'll add the test soon.

**Comment by enumag** [comment]
The test with custon CSV parser was failing for me so I fixed that as well (in separate commit). Please check if the fix is to your liking.

**Comment by tshelburne** [comment]
Thanks, this is great!

**Pull request merged**
