### PR TITLE
Fix wrong variable name

### PR DESCRIPTION
**Pull request by idr0id**
Undefined variable: key
> /vendors/nelmio/alice/src/Nelmio/Alice/Instances/Populator/Methods/ArrayAdd.php:82
> /vendors/nelmio/alice/src/Nelmio/Alice/Instances/Populator/Methods/ArrayAdd.php:37
> /vendors/nelmio/alice/src/Nelmio/Alice/Instances/Populator/Populator.php:85
> /vendors/nelmio/alice/src/Nelmio/Alice/Fixtures/Loader.php:303
> /vendors/nelmio/alice/src/Nelmio/Alice/Fixtures/Loader.php:143

### CODE REVIEW

**Comment by tshelburne** [comment]
Good catch - can you add a regression test that will show the problem before we merge?

**Comment by idr0id** [comment]
Yes I can. But I don't have idea how to mock static method ```StringUtil::singularify()```.

**Comment by tshelburne** [comment]
You don't have to worry about *everything* just for this PR - if you can just create a test that mimics the way you reached the exception, that's sufficient for this.

**Comment by idr0id** [comment]
@tshelburne I have done.

**Comment by tshelburne** [comment]
Thanks for this!

**Pull request merged**
