### PR TITLE
Add coverage codecov

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Comment by Yozhef** [comment]
@theofidry can you please reviw?

**Comment by theofidry** [comment]
I'm fine with enabling codecov but is there any way to avoid the big comment on each diff?

**Comment by Yozhef** [comment]
@theofidry Are you about this comment?
image

**Comment by theofidry** [comment]
@Yozhef yes

**Comment by Yozhef** [comment]
@theofidry so of course i will add

**Comment by Yozhef** [comment]
@theofidry  done =)

**Comment by theofidry** [comment]
Thank you @Yozhef

**Pull request merged**
