### PR TITLE
Small typo fix in Processors example

### PR DESCRIPTION
**Pull request by knugen**

### CODE REVIEW

**Comment by knugen** [comment]
One more note regarding this actually; I just implemented basically this exact scenario with password hashing and found that it needs to happen in the `preProcess` method or it won't get persisted. If somebody confirms I will update the PR.

**Comment by tshelburne** [comment]
@theofidry Can you confirm?

**Comment by theofidry** [comment]
That's correct, could you move the content of `postProcess()` into `preProcess()` please @knugen?

I checked the [`ProcessorInterface` the doc](https://github.com/nelmio/alice/blob/master/src/Nelmio/Alice/ProcessorInterface.php#L24) is up to date :)

**Comment by knugen** [comment]
Cool, done :)

**Comment by theofidry** [comment]
:+1:

**Comment by tshelburne** [comment]
Thanks guys, great catch.

**Pull request merged**
