### PR TITLE
Added mention of FOSUserBundle listener enabled by default.

### LINKED ISSUE #199: Processor with FOSUserBundle
Could I have information on what the [example of processor](https://github.com/nelmio/alice#processors) given really does? Is it really necessary because I forgot to use it and it seemed to work so just asking to clear things up.

### PR DESCRIPTION
**Pull request by theofidry**
Closes #199.

### CODE REVIEW

**Comment by tshelburne** [comment]
@theofidry @Seldaek Maybe it's just me, but I don't feel like we need to document another package's functionality - the example given in the README isn't supposed to say "here's how to use the `FOSUserBundle`", it's to say "here's where you can drop code to handle processing of your objects". If it's that confusing, we could just change the code in the methods to be something more benign, like `$object->password = PasswordHasher::hash($object->password);`. Thoughts?

**Comment by jenkoian** [comment]
@tshelburne yeah I think that's fair, my intention when I added the example was exactly that, an example. I only used fos user as an example as I thought it could prove a common scenario. If it's proving to hinder rather than help though, then feel free to update to something more generic :+1:

**Comment by theofidry** [comment]
Either way I'm fine: either use another example or add a mention for the example because otherwise is misleading.

**Comment by tshelburne** [comment]
@theofidry Fair point - are you going to update the PR, or do you want me to take care of it?

**Comment by theofidry** [comment]
@tshelburne if it doesn't bother you I would prefer that you do it I have trouble to keep up with everything right now^^

**Comment by tshelburne** [comment]
Alright, closing and updating independent of this.

**Comment by theofidry** [comment]
Thanks @tshelburne.

**Pull request closed without merging**
