### PR TITLE
Added new documentation for 2.0

### PR DESCRIPTION
**Pull request by tshelburne**
@Seldaek Updated changelog, upgrade, and readme (briefly) to describe 2.0.

### CODE REVIEW

**Comment by Seldaek** [comment]
@tshelburne please run with this and tag a 2.0 already :) It's quite obvious I don't have time to manage alice. I hoped I'd find time but it's not happening so go with what you feel is right, if it's wrong there's always a next release where things can be fixed!

**Comment by Seldaek** [comment]
Also, as soon as 2.0 is out more people will start migrating which will reduce the 1.x PR/issue load, so that'd be good too.

**Comment by tshelburne** [comment]
@Seldaek Ok - last we talked (admittedly a while ago), you wanted to see this before we went for it. Will take care of it.

**Comment by Seldaek** [comment]
Yeah I wanted to but I have to let go of some things because I can't do everything :)

**Pull request merged**
