### PR TITLE
proposal solution for #165

### PR DESCRIPTION
**Pull request by Markcial**
added a new pattern match for sequenced items addition by reference

### CODE REVIEW

**Comment by Markcial** [comment]
ping

**Comment by Seldaek** [comment]
Looks good to me but could you add it to the README as well?

**Comment by Markcial** [comment]
Ok, i will look for a moment today and I will update the proper README section

**Comment by Markcial** [comment]
ping!

**Comment by Seldaek** [comment]
Thanks!

**Pull request merged**
