### PR TITLE
Upgrade phpstan to v0.11.15

### PR DESCRIPTION
**Pull request by f3l1x**
Hi. Would like to use upgraded version of phpstan? I could repair some typos, etc.

Changes:
- upgrade phpstan to v0.11

### CODE REVIEW

**Comment by theofidry** [comment]
Sorry back from holidays. Did you check that the new PHPStan version is running with the current config?

**Comment by f3l1x** [comment]
Hi, I'm also little bit busy, I will let you know during the summer. It still alive. :-)

**Comment by f3l1x** [comment]
I've checked the configuration and it works. But the error report is huge.

Screenshot 2019-08-31 at 14 03 59

But it was huge before. :-)

It's ready to merge, if you want to.

**Comment by theofidry** [comment]
So far I’ve been using it only occasionally to have a cursory look so not
surprised. Thanks a lot for your help, will merge as soon as I’m back on
front of a computer:)

**Comment by f3l1x** [comment]
You're welcome. I like this tool. I can take a look at some errors from phpstan, if you mind.

**Comment by theofidry** [comment]
Any improvement is always welcome haha :)

**Comment by f3l1x** [comment]
Hi, have you checked this PR? :-) Any chance to get it merged?

**Comment by theofidry** [comment]
I’ll try to have a look tomorrow. If I didn’t have a look at it by midday
feel free to ping me again;

**Comment by theofidry** [comment]
Thanks @f3l1x

**Pull request merged**
