### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ireinhart**
clarify usage of references with includes

### CODE REVIEW

**Comment by Seldaek** [comment]
This seems like a bug we should fix though instead of documenting the workaroud :)

**Comment by ireinhart** [comment]
Did you have open an issue or pull request? In that case we can kill this pull request.

**Comment by Seldaek** [comment]
No I figured we can keep this open as a reminder but if you rather open a clear bug report instead it would be even better :)

**Comment by theofidry** [comment]
I can't reproduce it locally and I don't have it either in #340 (which add a few tests regarding the parsers). Try to update your version and if you still get this error re-open an issue for it.

Cheers

**Pull request closed without merging**
