### PR TITLE
Add third-party library

### PR DESCRIPTION
**Pull request by theofidry**

### CODE REVIEW

**Comment by Seldaek** [comment]
A third bundle? :(

I see it's a fork of the hautelook one. If you want to turn a fork into a legitimate project the least you can do is edit the README to have some information about what got changed and why it's better than the original.

It'd be great to try and talk to the hautelook folks as well, in case theirs isn't maintained anymore maybe they can add you as contributor, or mark theirs abandoned on packagist and point to yours?

**Comment by theofidry** [comment]
I've done the PR cd hautelook/alice-bundle#58. I would love to see this PR merge or have write access on the bundle to contribute more actively.

As for the changes, I'll update the README, aside from that the whole doc has been changed to reflect on the upgrade.

**Comment by theofidry** [comment]
@Seldaek [mention in the readme](https://github.com/theofidry/AliceBundle#disclamer)

**Comment by Seldaek** [comment]
Ok given there is a PR with quite a bit of support, and they don't maintain it much anymore, I am hoping this will resolve itself successfully and @hjr3 gives you repo access or such. Let's keep this PR open for now but ideally we can close it soon :)

**Comment by theofidry** [comment]
Hope you're right man, there not much use of having 4 bundles for the same thing :(

**Comment by hjr3** [comment]
I was away on leave for a while, catching back up on this stuff. @theofidry and I have spoken and I will move forward with giving him access.

**Comment by theofidry** [comment]
Great! :)

**Comment by Seldaek** [comment]
Excellent, and no stress @hjr3, holidays are ok too :)

**Pull request closed without merging**
