### PR TITLE
Moved documentation to `doc` folder

### PR DESCRIPTION
**Pull request by theofidry**
Follow up of #227

It makes quite a lot of files and some very short as I divided each chapter in a separate file. It may be the occasion to regroup a few ones together.

### CODE REVIEW

**Comment by jenkoian** [comment]
Personally I prefer the Ctrl-f friendly, all on one page approach, although I suppose that's not scalable.

**Comment by tshelburne** [comment]
I'm not against that approach, but from a maintenance perspective, I can say these docs have been a pain. @Seldaek thoughts?

**Comment by Seldaek** [comment]
Maybe it could be reorganized into a few chapters/files? I don't think exploding it all is that great because indeed you can't easily scroll/search into them, but yeah all in one is getting a bit too big.

**Comment by theofidry** [comment]
So, we have the following chapters:

* Creating Fixtures
* Fixture Ranges
* Faker Data
* Calling Methods
* Specifying Constructor Arguments
* Optional Data
* References
* Multiple References
* Handling Unique Constraints
* Fixture Inheritance
* Including files
* Variables
* Parameters
* Value Objects
* Custom Faker Data Providers
* Custom Setter
* Complete Sample
* Processors

And we need to regroup them. Well to start with I thing the `Complete Sample` could be kept in the README, it would give an visual idea of what's the library is doing.

We can also regroup Faker related topic:
* Faker Data
* Custom Faker Data Providers

But I have no idea about how to regroup what's left. Any idea?

**Comment by tshelburne** [comment]
What about something like "Basic Usage", "Advanced Usage", and then maybe "Extensions" to actually document the different ways you can extend the basic functionality?

**Comment by theofidry** [comment]
TOC propal:

1. [Installation](#installation)
2. [Getting Started](doc/getting-started.md)
  1. [Basic Usage](doc/getting-started.md#basic-usage)
  2. [Detailed Usage](doc/getting-started.md#detailed-usage)
  3. Complete Reference
    1. [Creating Fixtures](doc/creating-fixtures.md)
    2. [Fixture Ranges](doc/fixture-ranges.md)
    3. [Calling Methods](doc/calling-methods.md)
    4. [Specifying Constructor Arguments](doc/specifying-constructor-arguments.md)
    5. [Custom Setter](doc/custom-setter.md)
    6. [Optional Data](doc/optional-data.md)
    7. [References](doc/references.md)
    8. [Multiple References](doc/multiple-references.md)
    9. [Handling Unique Constraints](doc/handling-unique-constraints.md)
   10. [Processors](doc/processors.md)
3. Keep your fixtures dry
  1. [Fixture Inheritance](doc/fixture-inheritance.md)
  2. [Including files](doc/including-files.md)
  3. [Variables](doc/variables.md)
  4. [Parameters](doc/parameters.md)
3. Customize data generation
  1. [Random data with Faker](doc/faker-data.md)
  2. [Reuse generated data using objects value](doc/value-objects.md)
  3. [Custom Faker Data Providers](doc/custom-faker-data-providers.md)

**Comment by tshelburne** [comment]
Where are you suggesting the actual file boundaries would be?

**Comment by theofidry** [comment]
What do you mean?

**Comment by tshelburne** [comment]
Sorry, not clear - we're discussing breaking the docs up into files for maintainability and readability, but it's not clear to me where the file delineation is given your TOC. I love the separation and categorization, but this doesn't look like (at first glance) it drastically simplifies the number of files to be more searchable, as @Seldaek and @jenkoian were requesting. For instance, would "Complete Reference" be its own file?

**Comment by theofidry** [comment]
Ok yeah it wasn't clear. Updated accordingly

**Comment by tshelburne** [comment]
I can get behind that - @Seldaek @jenkoian how does that look?

**Comment by Seldaek** [comment]
Looks great to me thanks @theofidry

**Comment by theofidry** [comment]
Rebased and updated.

**Comment by tshelburne** [comment]
Thanks for this! Really helpful.

**Pull request merged**
