### PR TITLE
Add link to trappar/AliceGeneratorBundle

### PR DESCRIPTION
**Pull request by trappar**
Just published version 0.1.0 of this library which offers the ability to recursively convert existing Doctrine entities into Alice fixtures. Seems like a resource which fits right in with the other third part libraries 😄

### CODE REVIEW

**Comment by theofidry** [comment]
As it's tightly coupled to AliceBundle it should stay in AliceBundle IMO, not further.

**Comment by trappar** [comment]
The bundle itself doesn't require any component from AliceBundle to run, it only uses AliceBundle for testing. I haven't tested it with other libraries for loading the fixtures yet, but since all it does is generate normal Alice fixture yaml files, it should theoretically work with anything that loads Alice fixtures. Maybe I'll open a new pull request after I've done further testing.

**Comment by theofidry** [comment]
>The bundle itself doesn't require any component from AliceBundle to run

Then it shouldn't be a bundle :) You could rename it and make it a true library, and in it have a bridge for Symfony, e.g. like done in api-platform/core.

If it's published a PHP package and not a Symfony bundle then I see no reason not to include it in alice, but you should deliver that promise first (i.e. change the package name and test it without AliceBundle dependency)

**Comment by trappar** [comment]
I'll look into it. Thanks 😄

**Pull request closed without merging**
