### PR TITLE
Add Symfony Yaml PHP constants support integration

### LINKED ISSUE #827: Native Yaml constant support
I open this one because #680 was closed by the author.

As said in https://github.com/nelmio/alice/issues/680#issuecomment-282786124, this annotation should work:

```
<(AppBundle\Enum\CampaignType::GOOGLE_ADWORDS)>
```

Still, I think we should deprecate this in favor to the standard notation in order to avoid duplication and confusion.

Ref: http://symfony.com/blog/new-in-symfony-3-2-php-constants-in-yaml-files

WDYT?

I supposed you only accept features on the current 3.x stable?

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Closes #827

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I have to confess I don't understand why the tests are failing.

Could you please help me?

**Comment by theofidry** [comment]
Because the call is no longer `parse($fileContent)` [here](https://github.com/nelmio/alice/pull/829/files#diff-1bb89596d4482090faac6e8ff7ed270cR144) but it gets the constant as well depending of the YAML parser version

**Comment by Soullivaneuh** [comment]
Ok thanks, I'll try to simplify the call.

**Comment by Soullivaneuh** [comment]
Well, I can't because the yaml component does not accept parsing flags under SF 2.7.

I'll add conditional code on the tests.

**Comment by Soullivaneuh** [comment]
@theofidry I tried this: https://github.com/nelmio/alice/pull/829/files#diff-1bb89596d4482090faac6e8ff7ed270cR145

But this does not seem to change anything. :confused:

**Comment by theofidry** [comment]
https://github.com/nelmio/alice/pull/829/files#diff-1bb89596d4482090faac6e8ff7ed270cR158 should be updated to `Argument::cetera()` I think

**Comment by Soullivaneuh** [comment]
Aaaaannnnd all is fixed! \o/

**Comment by theofidry** [comment]
Thanks very much :)

**Pull request merged**
