### PR TITLE
Use preg_grep to match collection instances by mask

### PR DESCRIPTION
**Pull request by munkie**
*preg_grep* is much more faster alternative than iterating collection and applying *preg_match* on every instance array key.
I've used this script to random method performance  - https://gist.github.com/munkie/1d06214d8eaa2af349c1
Performance boost was upto 3-4x times with 1000 and 10000 items counts.

### CODE REVIEW

**Comment by tshelburne** [comment]
@munkie Thanks for this! Can you separate these additions out into individual PRs? My suggestion would be the `preg_grep` change as one PR, the fix in `Reference` with the test update in another, and finally the changes in `LoaderTest` in a third - this will allow us to discuss them independently, since they really aren't related.

**Comment by munkie** [comment]
@tshelburne I've splitted this PR into three:
* This PR now only introduces usage of _preg_grep_ to improve _Collection::random_ performance
* #260 LoaderTest cleanup
* #261 Add test for 0x multiplier in reference

**Comment by theofidry** [comment]
Cool, thanks @munkie!

**Comment by munkie** [comment]
@tshelburne I can provide same fix for 1.x branch, is it needed ?

**Comment by tshelburne** [comment]
Thanks!

**Pull request merged**
