### PR TITLE
Add support for steps with ranges (#539)

### PR DESCRIPTION
**Pull request by reinfi**
Resolves issue https://github.com/nelmio/alice/issues/539 for the step part.

Do I need to add the same functionality to FixtureRangeReferenceTokenParser?

### CODE REVIEW

**Comment by theofidry** [comment]
>Do I need to add the same functionality to FixtureRangeReferenceTokenParser?

Could you explain in more details what you mean? Sorry I'm a bit out of the context :)

Regarding the PR all green on my side for now :)

**Comment by reinfi** [comment]
The FixtureRangeReferenceTokenParser has the same logic for the range as the Denormalizer, but it is not used when I debug the loader test so I'm unsure if it also requires the step logic.

**Comment by theofidry** [comment]
Hm maybe it's missing out a test in the `LexerIntegrationTest` and `ParserIntegrationTest`. It's weird that this parser is not called at all

**Comment by reinfi** [comment]
That's what I did now. But I thought the parser should be called because it is designed to handle the user_{1..3} case. Now everything seems good, all tests are running :)

**Comment by theofidry** [comment]
All good then, thanks very much

**Pull request merged**
