### PR TITLE
Manage default instance without any properties

### LINKED ISSUE #198: Use fixture template
Is it possible to declared a template and use it as it is without altering a property?

I mean I have the following template:

```yml
Nelmio\Entity\User:
    user (template):
        username: <username()>
        name: <firstName()>
        lastname: <lastName()>
        city: <city()>
```

I use this template to override a property ok fine: that's  the usual use case. Now besides that, I which to use the template as it is to generate X users. At the moment I did not find another way than using the template while overriding a property:

```
    user{0..50} (extends template):
        username: <username()>
```

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #198.

cc @theofidry

### CODE REVIEW

**Comment by theofidry** [comment]
:+1:

**Comment by tshelburne** [comment]
Thanks!

**Comment by Soullivaneuh** [comment]
You're welcome. Could we have a new patch release for this? Thanks.

**Comment by Soullivaneuh** [comment]
ping @theofidry

**Comment by theofidry** [comment]
>ping @theofidry

?

**Comment by Soullivaneuh** [comment]
Well, I means ping @tshelburne.

Have to get some sleep.

**Comment by theofidry** [comment]
;)

**Comment by tshelburne** [comment]
Hey, yea, I just need to sit down and put together the changelist. I'll take care of it this afternoon (CST).

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by tshelburne** [comment]
v2.1.1 published.

**Comment by Soullivaneuh** [comment]
Thanks!

**Pull request merged**
