### PR TITLE
Moved to PSR-4

### PR DESCRIPTION
**Pull request by theofidry**
* flattened `src` and `tests` (removed `Nelmio/Alice`)
* used `autoload-dev` in `composer.json` to avoid to declare a custom `tests/bootstrap.php`

### CODE REVIEW

**Comment by Seldaek** [comment]
+1 for the autoload-dev change.

The rest I don't think it brings anything except breaking open PRs and potentially creating conflicts when trying to merge up from the 1.0 branch so -1 for me.

**Comment by theofidry** [comment]
Regarding the PR out of the 3 other opens, 2 of them are mine, but if you prefer to keep it I'll just put the autoload-dev change :)

**Comment by Seldaek** [comment]
Yeah it's not a huge deal I know but I also don't really see the advantage of skipping those two dirs.

**Comment by theofidry** [comment]
urg, does not seem to really work, I guess there is a kind of conflict since the two autoload statements are using the same prefix.

**Comment by theofidry** [comment]
Done

**Comment by Seldaek** [comment]
What was the issue? Because conflicting prefixes should not be one it should just try both. Anyway looks fine now.

**Comment by theofidry** [comment]
it was just me in local, I didn't reupdated the dependencies so the autoloader wasn't updated :)

**Comment by Seldaek** [comment]
Ok, `composer dump` ;)

**Pull request merged**
